apple_library(
  name = 'Signals',
  visibility = ['PUBLIC'],
  srcs = glob([
    '**/*.swift'
  ]),
  swift_version='3.0',
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework'
  ],
)
