apple_resource(
  name = 'LocalizationResources',
  files = glob([
    '*.lproj',
  ]),
  dirs = [
    'Sources/SwiftDate/SwiftDate.bundle',
  ],
)

apple_library(
  name = 'SwiftDate',
  visibility = ['PUBLIC'],
  srcs = glob([
    '**/*.swift'
  ]),
  swift_version='3.0',
  deps = [
    ':LocalizationResources'
  ],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework'
  ],
)
