apple_library(
  name = 'ReachabilitySwift',
  visibility = ['PUBLIC'],
  srcs = glob([
    'Reachability/*.swift',
  ]),
  deps = [

  ],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework'
  ],
)
